ADMIN = {
    "first_name": "amal",
    "last_name": "das",
    "email": "amaldas@example.com",
    "password": "pass1234",
}


USERS = [
    {
        "first_name": "naveen",
        "last_name": "s",
        "email": "naveen@example.com",
        "password": "pass1234",
    },
    {
        "first_name": "vikram",
        "last_name": "s",
        "email": "vikram@example.com",
        "password": "pass1234",
    },
    {
        "first_name": "madhavan",
        "last_name": "s",
        "email": "madhavan@example.com",
        "password": "pass1234",
    },
    {
        "first_name": "satheesh",
        "last_name": "s",
        "email": "satheesh@example.com",
        "password": "pass1234",
    },
    {
        "first_name": "vijay",
        "last_name": "s",
        "email": "vijay@example.com",
        "password": "pass1234",
    },
    {
        "first_name": "mani",
        "last_name": "s",
        "email": "mani@example.com",
        "password": "pass1234",
    },
    {
        "first_name": "priya",
        "last_name": "s",
        "email": "priya@example.com",
        "password": "pass1234",
    },
    {
        "first_name": "jeffy",
        "last_name": "s",
        "email": "jeffy@example.com",
        "password": "pass1234",
    },
    {
        "first_name": "saniya",
        "last_name": "s",
        "email": "saniya@example.com",
        "password": "pass1234",
    },
]

TASKS = [
    # Naveen - 6 tasks
    (
        "naveen@example.com",
        "Complete API documentation",
        "Document all Phase 1 endpoints",
        "Todo",
        "High",
        "2026-09-02",
    ),
    (
        "naveen@example.com",
        "Review authentication flow",
        "Review login and refresh flow",
        "In Progress",
        "Medium",
        "2026-09-03",
    ),
    (
        "naveen@example.com",
        "Test login endpoint",
        "Verify valid and invalid login scenarios",
        "Done",
        "High",
        "2026-08-30",
    ),
    (
        "naveen@example.com",
        "Update README",
        "Add project setup instructions",
        "Todo",
        "Low",
        "2026-09-05",
    ),
    (
        "naveen@example.com",
        "Review database models",
        "Verify model relationships",
        "In Progress",
        "Medium",
        "2026-09-06",
    ),
    (
        "naveen@example.com",
        "Check API responses",
        "Verify standard response format",
        "Todo",
        "Medium",
        "2026-09-08",
    ),
    # Vikram - 6 tasks
    (
        "vikram@example.com",
        "Review pull request",
        "Review authentication changes",
        "In Progress",
        "High",
        "2026-09-02",
    ),
    (
        "vikram@example.com",
        "Test refresh token",
        "Verify refresh token rotation",
        "Done",
        "High",
        "2026-08-29",
    ),
    (
        "vikram@example.com",
        "Check authorization",
        "Verify admin authorization rules",
        "Todo",
        "High",
        "2026-09-04",
    ),
    (
        "vikram@example.com",
        "Review migrations",
        "Check Alembic migration history",
        "Todo",
        "Medium",
        "2026-09-06",
    ),
    (
        "vikram@example.com",
        "Verify user pagination",
        "Check deterministic pagination",
        "In Progress",
        "Medium",
        "2026-09-07",
    ),
    (
        "vikram@example.com",
        "Review error handling",
        "Check API error responses",
        "Todo",
        "Low",
        "2026-09-09",
    ),
    # Madhavan - 6 tasks
    (
        "madhavan@example.com",
        "Implement task creation",
        "Create POST task endpoint",
        "In Progress",
        "High",
        "2026-09-01",
    ),
    (
        "madhavan@example.com",
        "Test task creation",
        "Write create task test cases",
        "Todo",
        "High",
        "2026-09-03",
    ),
    (
        "madhavan@example.com",
        "Review task model",
        "Verify task database columns",
        "Done",
        "Medium",
        "2026-08-28",
    ),
    (
        "madhavan@example.com",
        "Check task enums",
        "Verify status and priority enums",
        "Done",
        "Low",
        "2026-08-29",
    ),
    (
        "madhavan@example.com",
        "Add task validation",
        "Validate task request fields",
        "Todo",
        "Medium",
        "2026-09-05",
    ),
    (
        "madhavan@example.com",
        "Review task ownership",
        "Verify ownership requirements",
        "Todo",
        "High",
        "2026-09-08",
    ),
    # Satheesh - 6 tasks
    (
        "satheesh@example.com",
        "Test user registration",
        "Verify registration scenarios",
        "Done",
        "Medium",
        "2026-08-27",
    ),
    (
        "satheesh@example.com",
        "Test logout endpoint",
        "Verify refresh token revocation",
        "Done",
        "High",
        "2026-08-28",
    ),
    (
        "satheesh@example.com",
        "Test change password",
        "Verify password change flow",
        "In Progress",
        "High",
        "2026-09-02",
    ),
    (
        "satheesh@example.com",
        "Review password hashing",
        "Verify Argon2 implementation",
        "Todo",
        "Medium",
        "2026-09-04",
    ),
    (
        "satheesh@example.com",
        "Check inactive users",
        "Verify inactive user restrictions",
        "Todo",
        "High",
        "2026-09-06",
    ),
    (
        "satheesh@example.com",
        "Review JWT claims",
        "Check access token claims",
        "Todo",
        "Low",
        "2026-09-09",
    ),
    # Vijay - 6 tasks
    (
        "vijay@example.com",
        "Review pytest fixtures",
        "Check reusable test fixtures",
        "In Progress",
        "Medium",
        "2026-09-01",
    ),
    (
        "vijay@example.com",
        "Run authentication tests",
        "Run complete auth test suite",
        "Done",
        "High",
        "2026-08-30",
    ),
    (
        "vijay@example.com",
        "Check test coverage",
        "Review coverage report",
        "Done",
        "Medium",
        "2026-08-31",
    ),
    (
        "vijay@example.com",
        "Add task tests",
        "Prepare task integration tests",
        "Todo",
        "High",
        "2026-09-05",
    ),
    (
        "vijay@example.com",
        "Review test database",
        "Verify Neon test branch",
        "Todo",
        "Medium",
        "2026-09-06",
    ),
    (
        "vijay@example.com",
        "Clean test data",
        "Ensure test isolation",
        "Todo",
        "Low",
        "2026-09-10",
    ),
    # Mani - 5 tasks
    (
        "mani@example.com",
        "Review SQLAlchemy queries",
        "Check repository queries",
        "Todo",
        "Medium",
        "2026-09-02",
    ),
    (
        "mani@example.com",
        "Check database indexes",
        "Verify required indexes",
        "In Progress",
        "High",
        "2026-09-03",
    ),
    (
        "mani@example.com",
        "Review UUID7 implementation",
        "Verify UUID7 primary keys",
        "Done",
        "Medium",
        "2026-08-30",
    ),
    (
        "mani@example.com",
        "Check relationships",
        "Review user task relationship",
        "Todo",
        "High",
        "2026-09-06",
    ),
    (
        "mani@example.com",
        "Review transactions",
        "Verify commit and rollback flow",
        "Todo",
        "Medium",
        "2026-09-08",
    ),
    # Priya - 5 tasks
    (
        "priya@example.com",
        "Review FastAPI routes",
        "Check route organization",
        "In Progress",
        "Medium",
        "2026-09-02",
    ),
    (
        "priya@example.com",
        "Check Swagger documentation",
        "Verify endpoint documentation",
        "Todo",
        "Low",
        "2026-09-04",
    ),
    (
        "priya@example.com",
        "Test admin endpoints",
        "Verify admin user management",
        "Done",
        "High",
        "2026-08-30",
    ),
    (
        "priya@example.com",
        "Review dependency injection",
        "Check FastAPI dependencies",
        "Todo",
        "Medium",
        "2026-09-07",
    ),
    (
        "priya@example.com",
        "Verify HTTP status codes",
        "Check endpoint status codes",
        "Todo",
        "Medium",
        "2026-09-09",
    ),
    # Jeffy - 5 tasks
    (
        "jeffy@example.com",
        "Run Ruff checks",
        "Verify code quality",
        "Done",
        "Medium",
        "2026-08-31",
    ),
    (
        "jeffy@example.com",
        "Run mypy checks",
        "Verify type checking",
        "Done",
        "Medium",
        "2026-08-31",
    ),
    (
        "jeffy@example.com",
        "Review pre-commit hooks",
        "Check pre-commit configuration",
        "In Progress",
        "Low",
        "2026-09-02",
    ),
    (
        "jeffy@example.com",
        "Clean unused imports",
        "Remove unnecessary imports",
        "Todo",
        "Low",
        "2026-09-05",
    ),
    (
        "jeffy@example.com",
        "Review project structure",
        "Check application folder structure",
        "Todo",
        "Medium",
        "2026-09-08",
    ),
    # Saniya - 5 tasks
    (
        "saniya@example.com",
        "Prepare Phase 1 demo",
        "Prepare features for demonstration",
        "In Progress",
        "High",
        "2026-09-01",
    ),
    (
        "saniya@example.com",
        "Verify admin login",
        "Test admin credentials",
        "Done",
        "High",
        "2026-08-31",
    ),
    (
        "saniya@example.com",
        "Verify normal user login",
        "Test normal user credentials",
        "Done",
        "Medium",
        "2026-08-31",
    ),
    (
        "saniya@example.com",
        "Review Phase 1 requirements",
        "Compare implementation with requirements",
        "Todo",
        "High",
        "2026-09-04",
    ),
    (
        "saniya@example.com",
        "Prepare demo checklist",
        "Create final demonstration checklist",
        "Todo",
        "Medium",
        "2026-09-05",
    ),
]
